import type { Lead } from "./leadStore.js";

const DAY = 86400000;

function iso(offsetMs: number): string {
  return new Date(Date.now() + offsetMs).toISOString();
}

export function buildDemoLeads(): Lead[] {
  return [
    {
      id: "L_demo_001",
      ref: "DSCC-DEMO-001",
      source: "quote",
      status: "new",
      priority: "high",
      createdAt: iso(-2 * 60 * 60 * 1000),
      updatedAt: iso(-2 * 60 * 60 * 1000),
      fullName: "عبدالله الحربي",
      company: "شركة الواحة العقارية",
      email: "abdullah.h@example.com",
      phone: "+966551112233",
      city: "الرياض",
      projectType: "تشطيب فلل",
      services: ["تشطيب داخلي", "تصميم"],
      budget: "500,000 - 1,000,000 ريال",
      timeline: "خلال 3 أشهر",
      message: "أبحث عن شركة لتشطيب فيلتين في حي الياسمين، أحتاج عرض سعر تفصيلي.",
      notes: [],
      tags: ["VIP"],
    },
    {
      id: "L_demo_002",
      ref: "DSCC-DEMO-002",
      source: "contact",
      status: "contacted",
      priority: "normal",
      createdAt: iso(-3 * DAY),
      updatedAt: iso(-1 * DAY),
      fullName: "Sara Al-Otaibi",
      email: "sara.o@example.com",
      phone: "+966552223344",
      city: "Jeddah",
      projectType: "Office fit-out",
      services: ["Interior design", "Project management"],
      budget: "150,000 - 300,000 SAR",
      timeline: "Q3 2026",
      message: "Need to renovate our 400 sqm office in Jeddah business district.",
      notes: [
        {
          id: "N_demo_002a",
          body: "Called the client. Confirmed budget and visit scheduled for next week.",
          author: "admin",
          outcome: "answered",
          followUpAt: iso(2 * DAY),
          createdAt: iso(-1 * DAY),
        },
      ],
    },
    {
      id: "L_demo_003",
      ref: "DSCC-DEMO-003",
      source: "quote",
      status: "qualified",
      priority: "high",
      createdAt: iso(-7 * DAY),
      updatedAt: iso(-2 * DAY),
      fullName: "محمد القحطاني",
      company: "مجموعة القحطاني التجارية",
      email: "m.qahtani@example.com",
      phone: "+966553334455",
      city: "الدمام",
      projectType: "معرض تجاري",
      services: ["تصميم داخلي", "تنفيذ", "إضاءة"],
      budget: "أكثر من مليون ريال",
      timeline: "عاجل",
      message: "افتتاح معرض جديد بمساحة 800 م² في الدمام.",
      notes: [
        {
          id: "N_demo_003a",
          body: "اجتماع أولي تم. العميل جاد ولديه ميزانية مرنة.",
          outcome: "meeting_done",
          createdAt: iso(-4 * DAY),
        },
        {
          id: "N_demo_003b",
          body: "تم إعداد التصور المبدئي. متابعة لإرسال عرض السعر.",
          followUpAt: iso(1 * DAY),
          createdAt: iso(-2 * DAY),
        },
      ],
    },
    {
      id: "L_demo_004",
      ref: "DSCC-DEMO-004",
      source: "quote",
      status: "quotation_sent",
      priority: "normal",
      createdAt: iso(-12 * DAY),
      updatedAt: iso(-5 * DAY),
      fullName: "نورة السبيعي",
      email: "noura.s@example.com",
      phone: "+966554445566",
      city: "الرياض",
      projectType: "شقة سكنية",
      services: ["تصميم داخلي"],
      budget: "80,000 - 150,000 ريال",
      timeline: "خلال شهرين",
      message: "تصميم وتشطيب شقة 180 م² بحي النرجس.",
      notes: [
        {
          id: "N_demo_004a",
          body: "تم إرسال عرض السعر بقيمة 125,000 ريال. بانتظار الرد.",
          outcome: "quote_sent",
          followUpAt: iso(-1 * DAY),
          createdAt: iso(-5 * DAY),
        },
      ],
    },
    {
      id: "L_demo_005",
      ref: "DSCC-DEMO-005",
      source: "chatbot",
      status: "negotiation",
      priority: "urgent",
      createdAt: iso(-20 * DAY),
      updatedAt: iso(-1 * DAY),
      fullName: "Khalid Al-Mutairi",
      company: "Mutairi Holding",
      email: "khalid@example.com",
      phone: "+966555556677",
      city: "Riyadh",
      projectType: "Restaurant chain",
      services: ["Branding", "Interior design", "Build-out"],
      budget: "2M+ SAR",
      timeline: "ASAP - 6 months rollout",
      message: "Opening 4 restaurants across Riyadh and Jeddah this year.",
      notes: [
        {
          id: "N_demo_005a",
          body: "Quote accepted in principle. Negotiating payment milestones.",
          outcome: "quote_sent",
          createdAt: iso(-3 * DAY),
        },
        {
          id: "N_demo_005b",
          body: "Client requested 20% discount on second branch. Reviewing internally.",
          followUpAt: iso(0),
          createdAt: iso(-1 * DAY),
        },
      ],
      tags: ["VIP", "Multi-location"],
    },
    {
      id: "L_demo_006",
      ref: "DSCC-DEMO-006",
      source: "quote",
      status: "won",
      priority: "normal",
      createdAt: iso(-45 * DAY),
      updatedAt: iso(-10 * DAY),
      fullName: "فهد العنزي",
      email: "fahad.a@example.com",
      phone: "+966556667788",
      city: "الخبر",
      projectType: "مكتب إداري",
      services: ["تصميم", "تنفيذ"],
      budget: "200,000 ريال",
      timeline: "تم البدء",
      message: "مكتب 250 م² في الخبر.",
      notes: [
        {
          id: "N_demo_006a",
          body: "تم توقيع العقد. بدء العمل الأسبوع القادم.",
          outcome: "won",
          createdAt: iso(-10 * DAY),
        },
      ],
    },
    {
      id: "L_demo_007",
      ref: "DSCC-DEMO-007",
      source: "contact",
      status: "lost",
      priority: "low",
      createdAt: iso(-30 * DAY),
      updatedAt: iso(-15 * DAY),
      fullName: "Layla Hassan",
      email: "layla.h@example.com",
      phone: "+966557778899",
      city: "Mecca",
      projectType: "Hotel lobby renovation",
      services: ["Interior design"],
      budget: "Under 100,000 SAR",
      timeline: "Flexible",
      message: "Looking for budget-friendly lobby refresh.",
      notes: [
        {
          id: "N_demo_007a",
          body: "Client went with another vendor due to budget.",
          outcome: "lost",
          createdAt: iso(-15 * DAY),
        },
      ],
    },
  ];
}
