import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

export type Lang = "en" | "ar";

const STORAGE_KEY = "dscc_admin_lang";

const dict = {
  // Layout / nav
  brand: { en: "DSCC Admin", ar: "لوحة تحكم DSCC" },
  tagline: { en: "Saudi Arabia · Operations", ar: "المملكة العربية السعودية · العمليات" },
  nav_overview: { en: "Overview", ar: "نظرة عامة" },
  nav_leads: { en: "All Leads", ar: "جميع العملاء" },
  nav_quotes: { en: "Quote Requests", ar: "طلبات عروض الأسعار" },
  nav_chatbot: { en: "Chatbot Leads", ar: "عملاء روبوت المحادثة" },
  nav_contact: { en: "Contact Messages", ar: "رسائل التواصل" },
  nav_settings: { en: "Settings", ar: "الإعدادات" },
  sign_out: { en: "Sign out", ar: "تسجيل خروج" },
  language: { en: "العربية", ar: "English" },

  // Dashboard
  overview_title: { en: "Overview", ar: "نظرة عامة" },
  overview_desc: { en: "Live snapshot of inbound leads and pipeline activity.", ar: "لقطة مباشرة للعملاء الواردين ونشاط خط البيع." },
  stat_total: { en: "Total leads", ar: "إجمالي العملاء" },
  stat_total_hint: { en: "in last 30 days", ar: "خلال آخر 30 يوماً" },
  stat_new: { en: "New (untouched)", ar: "جدد (لم يُتواصل بعد)" },
  stat_new_hint: { en: "Awaiting first contact", ar: "بانتظار أوّل تواصل" },
  stat_quotes: { en: "Quote requests", ar: "طلبات أسعار" },
  stat_quotes_hint: { en: "From quotation requests", ar: "من مراحل طلبات الأسعار" },
  stat_chatbot: { en: "Chatbot leads", ar: "عملاء روبوت المحادثة" },
  stat_chatbot_hint: { en: "Generated by Sara", ar: "أنتجتهم سارة" },
  pipeline_title: { en: "Sales stages by status", ar: "مراحل المبيعات حسب الحالة" },
  pipeline_desc: { en: "Distribution of all leads across sales stages.", ar: "توزيع جميع العملاء على مراحل المبيعات." },
  source_title: { en: "Source breakdown", ar: "تصنيف المصدر" },
  source_desc: { en: "Where leads are coming from.", ar: "من أين يأتي العملاء." },
  recent_title: { en: "Recent activity", ar: "النشاط الأخير" },
  recent_desc: { en: "Latest 8 leads received.", ar: "آخر 8 عملاء واردين." },
  view_all: { en: "View all", ar: "عرض الكل" },
  no_leads_yet: { en: "No leads yet. They'll appear here as they come in.", ar: "لا يوجد عملاء بعد. سيظهرون هنا فور ورودهم." },
  unnamed_lead: { en: "Unnamed lead", ar: "عميل بدون اسم" },
  top_services: { en: "Top services", ar: "أكثر الخدمات طلباً" },
  top_cities: { en: "Top cities", ar: "أبرز المدن" },
  no_data_yet: { en: "No data yet.", ar: "لا توجد بيانات بعد." },

  // Leads list
  leads_title: { en: "All Leads", ar: "جميع العملاء" },
  leads_desc: { en: "Inbound inquiries, quote requests, and chatbot conversations in one place.", ar: "الاستفسارات الواردة وطلبات الأسعار ومحادثات الروبوت في مكان واحد." },
  quotes_title: { en: "Quote Requests", ar: "طلبات عروض الأسعار" },
  quotes_desc: { en: "Detailed quotation requests submitted via the website.", ar: "طلبات عروض أسعار تفصيلية مُرسلة عبر مراحل طلبات الأسعار." },
  chatbot_title: { en: "Chatbot Leads", ar: "عملاء روبوت المحادثة" },
  chatbot_desc: { en: "Leads captured by Sara, the AI sales engineer.", ar: "عملاء التقطتهم سارة، مهندسة المبيعات بالذكاء الاصطناعي." },
  contact_title: { en: "Contact Messages", ar: "رسائل التواصل" },
  contact_desc: { en: "General inquiries from the contact form.", ar: "استفسارات عامة من نموذج التواصل." },
  export_csv: { en: "Export CSV", ar: "تصدير CSV" },
  search_placeholder: { en: "Search name, company, email, notes, ref…", ar: "ابحث بالاسم أو الشركة أو البريد أو الملاحظات أو المرجع…" },
  all_statuses: { en: "All statuses", ar: "كل الحالات" },
  all_sources: { en: "All sources", ar: "كل المصادر" },
  all_cities: { en: "All cities", ar: "كل المدن" },
  all_services: { en: "All services", ar: "كل الخدمات" },
  city: { en: "City", ar: "المدينة" },
  service: { en: "Service", ar: "الخدمة" },
  no_match: { en: "No leads match your filters.", ar: "لا يوجد عملاء يطابقون معايير التصفية." },
  th_lead: { en: "Lead", ar: "العميل" },
  th_source: { en: "Source", ar: "المصدر" },
  th_city: { en: "City", ar: "المدينة" },
  th_services: { en: "Services", ar: "الخدمات" },
  th_status: { en: "Status", ar: "الحالة" },
  th_received: { en: "Received", ar: "استُلم" },
  unnamed: { en: "Unnamed", ar: "بدون اسم" },
  showing_x: { en: "Showing", ar: "عرض" },
  lead_singular: { en: "lead", ar: "عميل" },
  lead_plural: { en: "leads", ar: "عملاء" },

  // Lead detail
  back_to_leads: { en: "Back to leads", ar: "العودة إلى العملاء" },
  contact_card: { en: "Contact", ar: "معلومات التواصل" },
  full_name: { en: "Full name", ar: "الاسم الكامل" },
  company: { en: "Company", ar: "الشركة" },
  email: { en: "Email", ar: "البريد الإلكتروني" },
  phone: { en: "Phone", ar: "الهاتف" },
  created: { en: "Created", ar: "تاريخ الإنشاء" },
  project_request: { en: "Project request", ar: "تفاصيل المشروع" },
  submitted_via: { en: "Submitted via", ar: "أُرسل عبر" },
  from: { en: "from", ar: "من" },
  project_type: { en: "Project type", ar: "نوع المشروع" },
  project_size: { en: "Project size", ar: "حجم المشروع" },
  budget: { en: "Budget", ar: "الميزانية" },
  timeline: { en: "Timeline", ar: "الجدول الزمني" },
  source_action: { en: "Source action", ar: "إجراء المصدر" },
  intent: { en: "Intent (chatbot)", ar: "النية (الروبوت)" },
  services_label: { en: "Services", ar: "الخدمات" },
  recommended: { en: "Recommended (chatbot)", ar: "موصى به (الروبوت)" },
  message: { en: "Message", ar: "الرسالة" },
  conv_summary: { en: "Conversation summary", ar: "ملخّص المحادثة" },
  attachments: { en: "Attachments", ar: "المرفقات" },
  attachments_desc: { en: "Uploaded plans, drawings, BOQs and references.", ar: "المخطّطات والرسومات وقوائم الكميات والمراجع المرفوعة." },
  raw_payload: { en: "Raw payload", ar: "البيانات الأولية" },
  raw_desc: { en: "Full submitted data for reference.", ar: "البيانات المُرسلة كاملة للمرجعية." },
  internal_notes: { en: "Internal notes", ar: "ملاحظات داخلية" },
  notes_desc: { en: "Log calls, follow-ups, and outcomes.", ar: "سجّل المكالمات والمتابعات والنتائج." },
  add_note_ph: { en: "Add a note about this lead…", ar: "أضف ملاحظة حول هذا العميل…" },
  outcome_optional: { en: "Outcome (optional)", ar: "النتيجة (اختياري)" },
  out_called: { en: "Called", ar: "اتصلتُ" },
  out_emailed: { en: "Emailed", ar: "أرسلت بريداً" },
  out_meeting: { en: "Meeting scheduled", ar: "اجتماع مجدول" },
  out_quote: { en: "Quote sent", ar: "أُرسل العرض" },
  out_noanswer: { en: "No answer", ar: "لا رد" },
  out_notinterested: { en: "Not interested", ar: "غير مهتم" },
  add_note: { en: "Add note", ar: "إضافة ملاحظة" },
  saving: { en: "Saving…", ar: "جارٍ الحفظ…" },
  no_notes_yet: { en: "No notes yet.", ar: "لا توجد ملاحظات بعد." },
  delete_lead_q: { en: "Delete this lead?", ar: "حذف هذا العميل؟" },
  delete_lead_desc: { en: "This permanently removes the lead, notes, and history. This action cannot be undone.", ar: "سيتم حذف العميل وملاحظاته وسجله نهائياً. لا يمكن التراجع عن هذا الإجراء." },
  cancel: { en: "Cancel", ar: "إلغاء" },
  delete: { en: "Delete", ar: "حذف" },
  ref: { en: "Ref", ar: "المرجع" },
  received_at: { en: "received", ar: "استُلم" },
  prio_low: { en: "Low priority", ar: "أولوية منخفضة" },
  prio_normal: { en: "Normal priority", ar: "أولوية عادية" },
  prio_high: { en: "High priority", ar: "أولوية عالية" },
  prio_urgent: { en: "Urgent priority", ar: "أولوية عاجلة" },
  prio_low_short: { en: "Low", ar: "منخفضة" },
  prio_normal_short: { en: "Normal", ar: "عادية" },
  prio_high_short: { en: "High", ar: "عالية" },
  prio_urgent_short: { en: "Urgent", ar: "عاجلة" },

  // Login
  login_title: { en: "DSCC Admin", ar: "لوحة تحكم DSCC" },
  login_desc: { en: "Internal operations dashboard. Sign in with your admin token.", ar: "لوحة العمليات الداخلية. سجّل الدخول برمز المسؤول." },
  admin_token: { en: "Admin token", ar: "رمز المسؤول" },
  admin_token_ph: { en: "Enter your admin token", ar: "أدخل رمز المسؤول" },
  sign_in: { en: "Sign in", ar: "دخول" },
  signing_in: { en: "Signing in…", ar: "جارٍ الدخول…" },
  invalid_token: { en: "Invalid token. Check your ADMIN_TOKEN environment variable.", ar: "رمز غير صحيح. تحقّق من متغيّر البيئة ADMIN_TOKEN." },
  login_hint: { en: "Set ADMIN_TOKEN in your server environment to secure this dashboard. Default in development: dscc-dev-token.", ar: "اضبط ADMIN_TOKEN في بيئة الخادم لتأمين هذه اللوحة. القيمة الافتراضية في التطوير: dscc-dev-token." },

  // Settings
  settings_title: { en: "Settings", ar: "الإعدادات" },
  settings_desc: { en: "Configuration, integrations, and access for this admin dashboard.", ar: "الإعدادات والتكاملات وصلاحيات الوصول لهذه اللوحة." },
  auth_title: { en: "Authentication", ar: "المصادقة" },
  auth_desc: { en: "The dashboard is protected by a single admin token, configurable via the ADMIN_TOKEN environment variable on the API server.", ar: "اللوحة محميّة برمز مسؤول واحد، يُضبط عبر متغيّر البيئة ADMIN_TOKEN على خادم API." },
  storage_title: { en: "Data storage", ar: "تخزين البيانات" },
  storage_desc: { en: "Leads are stored as a JSON file on the API server, in a directory configurable via DATA_DIR (defaults to ./data). For Hostinger or any Node-capable host, mount that directory to a persistent volume.", ar: "تُحفظ بيانات العملاء كملف JSON على خادم API، في مجلّد قابل للضبط عبر DATA_DIR (الافتراضي ./data). على Hostinger أو أي استضافة Node، اربط هذا المجلّد بمساحة تخزين دائمة." },
  export_title: { en: "Export & integrations", ar: "التصدير والتكاملات" },
  export_desc: { en: "Lead data is structured to be portable. Use the CSV export on the leads page, or consume the API at /api/admin/leads with a bearer token. Webhook forwarding to Slack, Google Sheets, or a CRM can be added in the leads route.", ar: "بيانات العملاء منظّمة لتكون قابلة للنقل. استخدم تصدير CSV من صفحة العملاء، أو استدعِ /api/admin/leads بمفتاح Bearer. يمكن إضافة تمرير Webhook إلى Slack أو Google Sheets أو CRM داخل مسار العملاء." },
  deploy_title: { en: "Deployment", ar: "النشر" },
  deploy_desc: { en: "The dashboard ships as a static React build (Vite) and consumes a small Express API. Both can be hosted on Hostinger Node hosting.", ar: "تُبنى اللوحة كموقع React ثابت (Vite) وتستهلك واجهة Express صغيرة. كلاهما يمكن استضافته على Hostinger Node." },
  language_title: { en: "Language & appearance", ar: "اللغة والمظهر" },
  language_desc: { en: "Switch interface language and theme. Your choice is saved in this browser.", ar: "بدّل لغة الواجهة والمظهر. اختيارك محفوظ في هذا المتصفح." },

  // Statuses
  st_new: { en: "New", ar: "جديد" },
  st_contacted: { en: "Contacted", ar: "تم التواصل" },
  st_qualified: { en: "Qualified", ar: "مؤهَّل" },
  st_quotation_sent: { en: "Quotation Sent", ar: "أُرسل العرض" },
  st_negotiation: { en: "Negotiation", ar: "تفاوض" },
  st_won: { en: "Won", ar: "فائز" },
  st_lost: { en: "Lost", ar: "مفقود" },
  st_archived: { en: "Archived", ar: "مؤرشف" },

  // Sources
  src_quote: { en: "Quote Request", ar: "طلب عرض سعر" },
  src_contact: { en: "Contact Form", ar: "نموذج تواصل" },
  src_chatbot: { en: "Chatbot (Sara)", ar: "روبوت المحادثة (سارة)" },
  src_newsletter: { en: "Newsletter", ar: "النشرة البريدية" },
  src_other: { en: "Other", ar: "أخرى" },

  // 404
  nf_title: { en: "404 Page Not Found", ar: "404 الصفحة غير موجودة" },
  nf_desc: { en: "The page you are looking for does not exist.", ar: "الصفحة التي تبحث عنها غير موجودة." },
  nf_back: { en: "Back to dashboard", ar: "العودة إلى اللوحة" },

  file_label: { en: "file", ar: "ملف" },
  list_sep: { en: ", ", ar: "، " },

  // Time
  just_now: { en: "just now", ar: "الآن" },
  minutes_ago: { en: "min ago", ar: "د مضت" },
  hours_ago: { en: "h ago", ar: "س مضت" },
  days_ago: { en: "d ago", ar: "ي مضت" },

  // Notifications
  notifications_title: { en: "Notifications", ar: "الإشعارات" },
  no_notifications: { en: "No notifications yet.", ar: "لا توجد إشعارات بعد." },
  mark_all_read: { en: "Mark all as read", ar: "تعليم الكل كمقروء" },
  mark_read: { en: "Mark as read", ar: "تعليم كمقروء" },

  // Performance
  perf_conversion: { en: "Win rate", ar: "معدّل التحويل" },
  perf_conversion_hint: { en: "Won ÷ (Won + Lost)", ar: "الفائزون ÷ (الفائزون + المفقودون)" },
  perf_response: { en: "Avg first response", ar: "متوسّط زمن أوّل استجابة" },
  perf_response_hint: { en: "Lead created → first note", ar: "من ورود العميل إلى أوّل ملاحظة" },
  perf_response_hours: { en: "h", ar: "س" },
  perf_response_na: { en: "Not enough data", ar: "بيانات غير كافية" },
  perf_pipeline: { en: "Pipeline %", ar: "نسب مراحل المبيعات" },
  perf_pipeline_desc: { en: "Share of leads in each active stage.", ar: "نصيب كلّ مرحلة نشطة من العملاء." },
  perf_unassigned: { en: "Unassigned", ar: "غير معيّن" },
  perf_assigned: { en: "Assigned", ar: "معيّن" },

  // Follow-ups / Today
  nav_today: { en: "Today", ar: "اليوم" },
  today_title: { en: "Follow-ups today", ar: "متابعات اليوم" },
  today_desc: { en: "Overdue, today, and upcoming follow-ups recorded in lead notes.", ar: "المتابعات المتأخّرة واليومية والقادمة المسجّلة في ملاحظات العملاء." },
  today_overdue: { en: "Overdue", ar: "متأخّرة" },
  today_due: { en: "Due today", ar: "اليوم" },
  today_upcoming: { en: "Upcoming (7 days)", ar: "القادمة (7 أيام)" },
  today_none: { en: "Nothing here. You're all caught up.", ar: "لا يوجد شيء هنا. أحسنت!" },
  followup_at: { en: "Follow-up at", ar: "تاريخ المتابعة" },
  followup_optional: { en: "Schedule follow-up (optional)", ar: "جدولة متابعة (اختياري)" },
  open_lead: { en: "Open lead", ar: "فتح العميل" },

  // Assignment
  assigned_to: { en: "Assigned to", ar: "معيّن إلى" },
  unassigned: { en: "Unassigned", ar: "غير معيّن" },
  assign: { en: "Assign", ar: "تعيين" },
  filter_assigned: { en: "Assignee", ar: "المسؤول" },
  filter_priority: { en: "Priority", ar: "الأولوية" },
  all_assignees: { en: "All assignees", ar: "كل المسؤولين" },
  all_priorities: { en: "All priorities", ar: "كل الأولويّات" },
  no_operators_hint: { en: "Set the OPERATORS env var (comma-separated names) to enable assignment.", ar: "اضبط متغيّر البيئة OPERATORS (أسماء مفصولة بفاصلة) لتفعيل التعيين." },

  // Message templates
  templates_title: { en: "Quick messages", ar: "رسائل جاهزة" },
  templates_desc: { en: "Send via WhatsApp or Email with one click.", ar: "أرسل عبر واتساب أو البريد بنقرة واحدة." },
  tpl_pick: { en: "Pick a template", ar: "اختر قالباً" },
  tpl_lang: { en: "Template language", ar: "لغة القالب" },
  tpl_preview: { en: "Preview", ar: "معاينة" },
  tpl_send_wa: { en: "Send WhatsApp", ar: "إرسال واتساب" },
  tpl_send_email: { en: "Send Email", ar: "إرسال بريد" },
  tpl_copy: { en: "Copy text", ar: "نسخ النص" },
  tpl_copied: { en: "Copied to clipboard", ar: "تم النسخ" },
  tpl_no_phone: { en: "No phone on file for WhatsApp", ar: "لا يوجد رقم هاتف لإرسال واتساب" },
  tpl_no_email: { en: "No email on file", ar: "لا يوجد بريد إلكتروني" },
  tpl_subject: { en: "Email subject", ar: "موضوع البريد" },
  tpl_first_touch: { en: "First touch — Thank you & next steps", ar: "أوّل تواصل — شكر وخطوات قادمة" },
  tpl_followup: { en: "Polite follow-up after no answer", ar: "متابعة لطيفة بعد عدم الرد" },
  tpl_meeting: { en: "Propose a meeting", ar: "اقتراح اجتماع" },
  tpl_quote_ready: { en: "Quote ready — sending shortly", ar: "العرض جاهز — قيد الإرسال" },
  tpl_quote_sent: { en: "Quote sent — awaiting feedback", ar: "تم إرسال العرض — بانتظار الردّ" },
  tpl_thank_you: { en: "Thank you for choosing DSCC", ar: "شكراً لاختيارك DSCC" },

  // Saved views
  saved_views: { en: "Saved views", ar: "العروض المحفوظة" },
  save_view: { en: "Save current view", ar: "حفظ هذا العرض" },
  view_name_ph: { en: "View name (e.g. Riyadh urgent)", ar: "اسم العرض (مثل: الرياض عاجل)" },
  apply_view: { en: "Apply", ar: "تطبيق" },
  delete_view: { en: "Delete", ar: "حذف" },
  no_saved_views: { en: "No saved views yet.", ar: "لا توجد عروض محفوظة." },
  view_saved: { en: "View saved", ar: "تم حفظ العرض" },
} as const;

export type TKey = keyof typeof dict;

interface I18nCtx {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (k: TKey) => string;
  dir: "ltr" | "rtl";
}

const Ctx = createContext<I18nCtx | null>(null);

function detect(): Lang {
  try {
    const saved = localStorage.getItem(STORAGE_KEY);
    if (saved === "ar" || saved === "en") return saved;
  } catch {}
  return "ar";
}

export function I18nProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => detect());

  useEffect(() => {
    const dir = lang === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = lang;
    document.documentElement.dir = dir;
    try { localStorage.setItem(STORAGE_KEY, lang); } catch {}
  }, [lang]);

  const setLang = (l: Lang) => setLangState(l);
  const t = (k: TKey) => dict[k]?.[lang] ?? dict[k]?.en ?? String(k);

  return (
    <Ctx.Provider value={{ lang, setLang, t, dir: lang === "ar" ? "rtl" : "ltr" }}>
      {children}
    </Ctx.Provider>
  );
}

export function useI18n() {
  const v = useContext(Ctx);
  if (!v) throw new Error("useI18n must be used within I18nProvider");
  return v;
}
